---
title: "Hw9_maheeka"
author: "Maheeka"
date: "2023-04-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
av <- read.csv("https://raw.githubusercontent.com/fivethirtyeight/data/master/avengers/avengers.csv", stringsAsFactors = FALSE)

av.new <- av %>% gather(key = Time1, value = Death, c(11,13,15,17,19)) 

av.new <- av.new %>% gather(key = Time2, value = Return, c(11,12,13,14,15))

av.new$Time1 = parse_number(av.new$Time1)
av.new$Time2 = parse_number(av.new$Time2)

#If Hulk is sent to the future and we follow his adventures there, he’s not dead.

hulk = av.new %>% filter(Name.Alias == "Robert Bruce Banner", Return == "YES", Death == "YES")
hulk
#since Hulk has returned in the year he died, he's not dead.
```
Tess' ?
```{r}
#If Iron Man fakes his death to chill out for a while but all his friends (and the reader) know he’s just kicking it somewhere, he didn’t die.
ironman = av.new %>% filter(Name.Alias == "Anthony Edward Stark", Return == "NO", Death == "YES")
ironman
```
Iron man died in avengers endgame and never returned 

```{r}
#leah pt 2: If Iron Man fakes his death to chill out for a while but all his friends (and the reader) know he’s just kicking it somewhere, he didn’t die.
iron = av.new %>% filter(Name.Alias == "Tony Masters", Time1 == "1", Death == "NO")
#he didn't die because the time 2 still occurs. 
```